

export enum RtcMessage {
    RTC_CONNECT = "RTC_CONNECT",
    RTC_OFFER = "RTC_OFFER",
    RTC_ANSWER = "RTC_ANSWER",
    RTC_ICE = "RTC_ICE",
    RTC_DESCRIPTION = "RTC_DESCRIPTION",
    
    RTC_ADD_INBOUND_TRANSMISSION = "RTC_ADD_INBOUND_TRANSMISSION",
    RTC_CHANGE_INBOUND_TRANSMISSION = "RTC_CHANGE_INBOUND_TRANSMISSION",
    RTC_REMOVE_INBOUND_TRANSMISSION = "RTC_REMOVE_INBOUND_TRANSMISSION",
    RTC_OUTBOUND_TRANSMISSION_STATE_CHANGE = "RTC_OUTBOUND_TRANSMISSION_STATE_CHANGE",

}