import { ObservedMap, ObservedPlainMapMap } from "react-use-listeners";
import { WebRtcManager } from "../WebRtcManager";
import { InboundController } from "./InboundController";
import { AddInboundControllerPayload, RemoveInboundControllerPayload, ModifyInboundControllerPayload } from "./Controller";
import { LocalController, LocalStreamController } from "./LocalController";
import { OutboundController, OutboundStreamController } from "./OutboundController";
import { MediaObject } from "../Media/MediaDevicesManager";
export declare class ControllerManager {
    webRtcManager: WebRtcManager;
    outboundControllers: ObservedPlainMapMap<OutboundController>;
    localControllers: ObservedMap<LocalController>;
    inboundControllers: ObservedMap<InboundController>;
    logging: boolean;
    constructor(webRtcManager: WebRtcManager, logging?: boolean);
    getInboundController(controllerId: string): InboundController<MediaObject> | undefined;
    getLocalController(controllerId: string): LocalController<MediaObject> | undefined;
    inboundControllerAdded(fromSid: string, payload: AddInboundControllerPayload): void;
    inboundControllerRemoved(fromSid: string, payload: RemoveInboundControllerPayload): void;
    inboundControllerModified(fromSid: string, payload: ModifyInboundControllerPayload): void;
    addLocalController(localController: LocalController): void;
    createOrGetOutboundStreamController(remoteSid: string, label: string, localController: LocalStreamController): OutboundStreamController;
    removeOutboundController(remoteSid: string, resourceId: string): void;
    removeLocalController(controllerId: string): void;
    sendAddInboundController(remoteSid: string, payload: AddInboundControllerPayload): void;
    sendModifyInboundController(remoteSid: string, payload: ModifyInboundControllerPayload): void;
    sendRemoveInboundController(remoteSid: string, payload: RemoveInboundControllerPayload): void;
    getOutboundControllers(): ObservedPlainMapMap<OutboundController<MediaObject>>;
    getLocalControllers(): ObservedMap<LocalController<MediaObject>>;
    getInboundControllers(): ObservedMap<InboundController<MediaObject>>;
}
